package com.roadsidehelp.api.config.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    ACCESS_DENIED,
    ENTITY_ALREADY_EXISTS,
    BAD_REQUEST,
    OTP_EXPIRED,
    OTP_INVALID,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_NOT_FOUND,
    REFRESH_TOKEN_ALREADY_REVOKED,
    NO_ACTIVE_SESSIONS,
    INTERNAL_ERROR,
    TOKEN_EXPIRED,
    INVALID_TOKEN,
    DATA_NOT_FOUND,
    EMAIL_NOT_VERIFIED

}
